### ISSUE TITLE
Error: Method visitTsType not implemented.

### ISSUE THREAD

**Issue by surzhik** [renzp94/jsx-css-scoped-loader#1]
Hi.
I am following https://github.com/renzp94/jsx-css-scoped-loader/blob/main/playground/webpack.config.js, trying to use this lib on a Windows environment.
Unfortunately, I have the following issue:

```
Compiled with problems:

ERROR in ./src/index.tsx

Module build failed (from ./node_modules/@renzp/jsx-scoped-loader/lib/index.js):
Error: Method visitTsType not implemented.
 
```

**Comment by renzp94** [comment]
This issue looks like an error with SWC loader, and I have already raised the issue.[swc-loader#78](https://github.com/swc-project/swc-loader/issues/78)

**Comment by renzp94** [comment]
You can try downloading the @ swc/core for the corresponding platform, and I can try it on Window (Intel). The node version is 18.16.1. You can try downloading the corresponding platform version.
